apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-example-app
  labels:
    app: php-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-example-app
  template:
    metadata:
      labels:
        app: php-example-app
    spec:
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: copy-app
        image: docker.k8s.kuops.com/php-example-app:master-2
        command: ['sh', '-c', '/bin/cp -rp /var/www /tmp']
        volumeMounts:
        - name: php-app
          mountPath: /tmp/www
      - name: php-artisan
        image: docker.k8s.kuops.com/php-example-app:master-2
        command: ['sh', '-c', 'cd /var/www && php artisan voyager:install --with-dummy']
        volumeMounts:
        - name: php-app
          mountPath: /var/www
        - name: conf
          mountPath: /var/www/.env
          subPath: .env
      containers:
      - name: nginx
        image: kuopsme/nginx:1.15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: CONFIG_HASH
          value: ${CONFIG_HASH}
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: conf
          mountPath: /var/www/.env
          subPath: .env
        - name: php-app
          mountPath: /var/www
      - name: php-fpm
        image: kuopsme/php:7.2-fpm-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: conf
          mountPath: /var/www/.env
          subPath: .env
        - name: php-app
          mountPath: /var/www
      volumes:
      - name: conf
        configMap:
          name: php-example-cm
      - name: php-app
        emptyDir: {}
