apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      initContainers:
      - name: copy-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ['sh', '-c', '/bin/cp -rp /var/www /tmp']
        volumeMounts:
        - name: php-app
          mountPath: /tmp/www
      - name: php-artisan
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ['sh', '-c', 'cd /var/www && php artisan voyager:install --with-dummy']
        volumeMounts:
        - name: php-app
          mountPath: /var/www
        - name: conf
          mountPath: /var/www/.env
          subPath: .env
      containers:
      - name: nginx
        image: kuopsme/nginx:1.15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: conf
          mountPath: /var/www/.env
          subPath: .env
        - name: php-app
          mountPath: /var/www
      - name: php-fpm
        image: kuopsme/php:7.2-fpm-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: conf
          mountPath: /var/www/.env
          subPath: .env
        - name: php-app
          mountPath: /var/www
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
      volumes:
      - name: conf
        configMap:
          name: {{ .Values.configmap.name }}
      - name: php-app
        emptyDir: {}
