kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-storage
  labels:
    app: {{ template "mysql.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
