apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: {{ template "mysql.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
  selector:
    app: {{ template "mysql.name" . }}
  clusterIP: {{ .Values.service.clusterIP }}
